# these are sensors for instrumentation / debug only (not core to SMU functionality)
sensor:
  - platform: tmp1075n
    id: temp_fets
    address: 0x48
    name: "${name} Temp FETs"
    update_interval: 1s
  - platform: tmp1075n
    id: temp_buckboost
    address: 0x49
    name: "${name} Temp Buck-boost"
    update_interval: 1s

  - platform: ina219
    address: 0x40
    shunt_resistance: 0.01 ohm
    current:
      name: "Vin Current"
    power:
      name: "Vin Power"
    bus_voltage:
      name: "Vin Bus Voltage"
    update_interval: 1s
  - platform: ina219
    address: 0x44
    shunt_resistance: 0.01 ohm
    current:
      name: "Vconv Current"
    power:
      name: "Vconv Power"
    bus_voltage:
      name: "Vconv Bus Voltage"
    update_interval: 1s

text_sensor:
  - platform: version
    name: "${name} Version"
    internal: true
  - platform: wifi_info
    mac_address:
      name: "${name} Mac Wifi"
      internal: true
